"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Garrett"
email = "garrett.o@agilebits.com"

[signing]
sign-all = true
backend = "ssh"
backends.ssh.program = "/Applications/1Password.app/Contents/MacOS/op-ssh-sign"
key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDF+VTxDbi6XBbGNueF5ntXO6iT3v2idQed64vYkWSvh"

[git]
private-commits = "description(glob:'private:*')"
push-new-bookmarks = true

[ui]
# HACK: https://github.com/martinvonz/jj/issues/3753
editor = ["nvim", "--cmd", "let g:launched_by_shell=1"]
merge-editor = "nvimdiff"
show-cryptographic-signatures = true

[merge-tools.nvimdiff]
program = "nvim"
merge-args = ["-c", "JJdiff", "-d", "$left", "$output", "$right"]

[template-aliases]
"format_short_cryptographic_signature(sig)" = "if(sig, '', '(no sig)')"
